version: "3.7"
services:
  redis:
    image: redislabs/redisearch:latest
    container_name: redisearch
    ports:
      - 6379:6379
    network_mode: host
  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_HOST=localhost
    ports:
      - 26379:26379
    network_mode: host