version: "3.7"
services:
  redis-graph:
    image: redislabs/redisgraph:edge
    ports:
      - 6379
    network_mode: host
  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_HOST=localhost
    ports:
      - 26379:26379
    network_mode: host