version: "3.7"

services:
  auth:
    tty: true
    image: hydre/auth:edge-dgraph
    container_name: auth-dgraph
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NAME: dgraph
    network_mode: host
    environment:
      LOCALHOST: "true"
      DEBUG: "auth*"
      DGRAPH_RPC_URI: "0.0.0.0:9080"
  zero:
    image: dgraph/dgraph:latest
    container_name: dgraph_zero
    network_mode: host
    restart: "no"
    command: dgraph zero --my=localhost:5080
  alpha:
    image: dgraph/dgraph:latest
    container_name: dgraph_alpha
    network_mode: host
    restart: "no"
    command: dgraph alpha --my=localhost:7080 --lru_mb=2048 --zero=localhost:5080
  ratel:
    image: dgraph/dgraph:latest
    network_mode: host
    command: dgraph-ratel
