name: CI
on:
  push:
    branches:
      - edge
    tags:
      - v*
jobs:
  edge:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/edge'
    strategy:
      matrix:
        image: [mongo, neo4j, dgraph]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: hydre/auth
          tags: edge-${{ matrix.image }}
          username: sceat
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          buildargs: NAME=${{ matrix.image }}
          cache: true

  stable:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        image: [mongo, neo4j, dgraph]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Build and publish
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: hydre/auth
          tags: ${{ env.RELEASE_VERSION }}-${{ matrix.image }}
          username: sceat
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          buildargs: NAME=${{ matrix.image }}
          cache: true
