name: Docker
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u sceat --password-stdin
      - name: Publish edge
        if: github.ref == 'refs/heads/master'
        run: |
          docker build --tag hydre/auth:edge-mongo --build-arg NAME=mongo .
          docker build --tag hydre/auth:edge-bolt --build-arg NAME=bolt .
          docker build --tag hydre/auth:edge-dgraph --build-arg NAME=dgraph .
      - name: Publish stable
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$(echo $VERSION | sed -e 's/^v//')
          docker build --tag hydre/auth:${VERSION}-mongo --build-arg NAME=mongo .
          docker build --tag hydre/auth:${VERSION}-bolt --build-arg NAME=bolt .
          docker build --tag hydre/auth:${VERSION}-dgraph --build-arg NAME=dgraph .
