name: Release
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  edge:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Log in to docker hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u sceat --password-stdin
      - name: Build edge mongo
        run: docker build --tag hydre/auth:edge-mongo --build-arg NAME=mongo .
      - name: Build edge bolt
        run: docker build --tag hydre/auth:edge-bolt --build-arg NAME=neo4j .
      - name: Build edge dgraph
        run: docker build --tag hydre/auth:edge-dgraph --build-arg NAME=dgraph .
      - name: Publish edge mongo
        run: docker push hydre/auth:edge-mongo
      - name: Publish edge bolt
        run: docker push hydre/auth:edge-bolt
      - name: Publish edge dgraph
        run: docker push hydre/auth:edge-dgraph

  stable:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Log in to docker hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u sceat --password-stdin
      - name: Build stable mongo
        run: docker build --tag hydre/auth:${$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')}-mongo --build-arg NAME=mongo .
      - name: Build hydre/auth:edge-neo4j
        run: docker build --tag hydre/auth:${$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')}-bolt --build-arg NAME=neo4j .
      - name: Build hydre/auth:edge-dgraph
        run: docker build --tag hydre/auth:${$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')}-dgraph --build-arg NAME=dgraph .
      - name: Publish hydre/auth:edge-mongo
        run: docker push hydre/auth:${$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')}-mongo
      - name: Publish hydre/auth:edge-neo4j
        run: docker push hydre/auth:${$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')}-bolt
      - name: Publish hydre/auth:edge-dgraph
        run: docker push hydre/auth:${$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')}-dgraph
