name: Docker
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13.12
      - name: echo
        run: |
          echo "${{ github.ref }}"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo $VERSION
          VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo $VERSION
      - run: export DEBUG="auth*"
      - run: npm i -g pnpm
      - run: pnpm run install:all
      - name: Run tests
        run: pnpm run test:dgraph
  push:
    # Ensure test job passes before pushing image.
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u sceat --password-stdin
#       - name: Publish edge
#         if: github.ref == 'master'
#         run: |
#           docker build . --tag hydre/auth:edge-mongo --build-arg mongo
#           docker build . --tag hydre/auth:edge-bolt --build-arg bolt
#           docker build . --tag hydre/auth:edge-dgraph --build-arg dgraph
#       - name: Publish stable
#         if: startsWith(github.ref, 'refs/tags/')
#         run: |
#           VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
#           VERSION=$(echo $VERSION | sed -e 's/^v//')
#           docker build . --tag hydre/auth:${VERSION}-mongo --build-arg mongo
#           docker build . --tag hydre/auth:${VERSION}-bolt --build-arg bolt
#           docker build . --tag hydre/auth:${VERSION}-dgraph --build-arg dgraph


